services:
  maillist:
    image: "${IMAGE_NAME}"
    environment:
      - MAILLIST_DB_PATH=/usr/data/maillist.db
      - MAILLIST_BIND_JSON=:8080
      - MAILLIST_BIND_GRPC=:8081
    ports:
      - "8080:8080"
    volumes:
      - ./db:/usr/data
      - ./src:/app/src